---
- name: restart network
  raw: /etc/netstart
- name: restart ezjail
  service: name=ezjail state=restarted
- name: restart pf
  service: name=pf state=restarted
- name: restart sshd
  service: name=sshd state=restarted
- name: restart ntpd
  service: name=ntpd state=restarted
- name: reload sysctl
  raw: service sysctl reload
  register: command_result
  failed_when: "command_result.stderr"
