---
- name: Enable pf in rc.conf
  service:
    name: pf
    enabled: yes
  notify: restart network

- name: Setup pf.conf
  template:
    src: pf.conf
    dest: /etc/pf.conf
  notify: restart network
  tags: pf-conf

- name: Enable gateway in rc.conf
  command: sysrc gateway_enable=YES
  notify: restart network
