---
ploy_bootstrap_data_pool_name: "tank"
ploy_bootstrap_raid_mode: "detect"
ploy_bootstrap_data_pool_devices: ""
ploy_bootstrap_geli: no
ploy_bootstrap_zpool_version: 28
ploy_ezjail_install_host: "ftp.freebsd.org"
jails_dir: /usr/jails
jails_zfs_root: tank/jails
zfs_checksum: fletcher4
pkg_txz_url: http://pkg.freebsd.org/freebsd:9:x86:64/quarterly/Latest/pkg.txz
jails_pkg_url: "pkg+http://pkg.freeBSD.org/${ABI}/latest"
ipnat_jail_networks:
    - 10.0.0.0/8
ipnat_rules: []
