---
ploy_bootstrap_data_pool_name: "tank"
ploy_bootstrap_raid_mode: "detect"
ploy_bootstrap_data_pool_devices: ""
ploy_bootstrap_geli: no
ploy_bootstrap_zpool_version: 28
ploy_ezjail_install_host: "ftp.freebsd.org"
jails_dir: /usr/jails
ploy_jails_zfs_root:  "{{ ploy_bootstrap_data_pool_name }}/jails"
zfs_checksum: fletcher4
pkg_txz_url: http://pkg.freebsd.org/freebsd:10:x86:64/quarterly/Latest/pkg.txz
jails_pkg_url: "pkg+http://pkg.freeBSD.org/${ABI}/latest"
pf_nat_jail_networks:
    - 10.0.0.0/8
pf_nat_rules: []
pf_nat_interface: "{{ansible_default_ipv4.interface}}"
ploy_jail_host_sshd_listenaddress: "{{ ansible_default_ipv4.address }}"
ploy_jail_host_pkg_repository_kind: "quarterly"
ploy_jail_host_pkg_repository_url: "pkg+http://pkg.freeBSD.org/${ABI}/{{ ploy_jail_host_pkg_repository_kind }}"
ploy_jail_host_pkg_repository: |
    FreeBSD-custom: {
        url: "{{ ploy_jail_host_pkg_repository_url }}",
        mirror_type: "srv",
        enabled: yes
    }
ploy_root_user_name: "{{ploy_user | default('root')}}"
ploy_root_home_path: "{{ '/' if ploy_root_user_name == 'root' else '/usr/home/' }}{{ploy_root_user_name}}"
ploy_jail_host_cloned_interfaces: lo1
ploy_jail_host_default_jail_interface: lo1
